### ISSUE TITLE
Add a link to the sources

### ISSUE THREAD

**Issue by linean** [MakeItEasyDev/Jetpack-Compose-Animated-Shuffle-Vertical-Grid#1]
Hello, I've noticed you copied my article and example app without any references. Could you please make sure to link it everywhere (yt,fb,github)? 

https://github.com/linean/AnimatedVerticalGrid

Thanks! 🤝

**Comment by MakeItEasyDev** [comment]
Hai Linean, Yes i referred your code.

Thanks!!!
